# Generated by Django 5.1.1 on 2024-10-24 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('rep_category_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report_price',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=60)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('rep_id', models.AutoField(primary_key=True, serialize=False)),
                ('rep_url', models.CharField(max_length=500)),
                ('rep_title', models.CharField(max_length=500)),
                ('publish_date', models.CharField(max_length=50)),
                ('pages', models.IntegerField()),
                ('rep_category_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Datatable',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('overview', models.TextField()),
                ('table_content', models.TextField()),
                ('list_content', models.TextField()),
                ('rep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.title')),
            ],
        ),
    ]
