# Generated by Django 5.1.1 on 2024-11-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
