# Generated by Django 5.1.1 on 2024-11-12 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_title', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label', models.CharField(max_length=60)),
                ('rep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.title')),
            ],
        ),
    ]
